caption: "Оцени видео от 1 до 10 \U0001F639\U0001F496\nкстати у меня в сторис есть\
  \ много интересного для тебя \n\n#знакомстваукраина #знакомствакиев #знакомстваодесса #девушкиукраины #девушкиукраина #девушкиодессы #девушкикиев #девушкиодесса #девушкихарькова #девушкихарьков #девушкидонецк #девушкидонецка #девушкиднепр#знакомства #знакомстваонлайн\n\
  #дружба #свидание #отношения #ищудевушку #красивыедами #познакомиться #ищужену #ищулюбовь #ищумужа #хочузамуж #znakomstva #ищужену #ищуженщину #женюсь #сайтзнакомств\n"
is_easter_egg: false
is_feed: true
is_story: false
