caption: 'Нормальная адекватная ищу мужчину для серьёзных отношений. Работаю баристой,
  живу на съёмной квартире. Контакты по ссылке в профиле


  #знакомстваукраина #знакомствакиев #знакомстваодесса #девушкиукраины #девушкиукраина #девушкиодессы #девушкикиев #девушкиодесса #девушкихарькова #девушкихарьков #девушкидонецк #девушкидонецка #девушкиднепр#знакомства #знакомстваонлайн

  #дружба #свидание #отношения #ищудевушку #красивыедами #познакомиться #ищужену #ищулюбовь #ищумужа #хочузамуж #znakomstva #ищужену #ищуженщину #женюсь #сайтзнакомств

  '
is_easter_egg: false
is_feed: true
is_story: false
