caption: "Давай будем знакомиться? Я Ира а ты? \nМои контакты в профиле\n\n#знакомстваукраина #знакомствакиев #знакомстваодесса #девушкиукраины #девушкиукраина #девушкиодессы #девушкикиев #девушкиодесса #девушкихарькова #девушкихарьков #девушкидонецк #девушкидонецка #девушкиднепр#знакомства #знакомстваонлайн\n\
  #дружба #свидание #отношения #ищудевушку #красивыедами #познакомиться #ищужену #ищулюбовь #ищумужа #хочузамуж #znakomstva #ищужену #ищуженщину #женюсь #сайтзнакомств\n"
is_easter_egg: false
is_feed: true
is_story: false
