caption: "Взрослая женщина и понимающая женщина. Ищу мужчину для отношений. Буду ласковая\
  \ нежная и заботливая. Пишите если понравилась. \nСсылка на контакты в профиле\n"
is_easter_egg: false
is_feed: true
is_story: false
