caption: "Карина 26 лет. Хочу познакомиться с хорошим и интересным мужчиной. Пишите\
  \ по ссылке в профиле если понравилась. Я настоящая и буду искать любовь\n\n#знакомствадлясерьезныхотношений\
  \ #знакомство #знакомства #ищупарня #ищудевушку #ищулюбовь #знакомстваукраина #знакомствароссия\
  \ \n#знакомство#знакомства #знакомстваонлайнэ #знакомствадлясерьезныхотношений \n\
  #acquaintanceforaseriousrelationship #acquaintance #dating #lookingforaguy #lookingforagirl\
  \ #lookingforlove #datingUkraine #datingRussia\n #dating #tiktok #musically\n"
is_easter_egg: false
is_feed: true
is_story: false
