caption: 'ะะพะฑัะพะต ัััะพ ะบะพัััะฐ ๐๐


  ะัะพ ะผะฝะต ะฝะต ะฟัะพัะธะฒ ะฝะฐะฟะธัะฐัั ะถะดะดั ะฟะพ ัััะปะบะต ะฒ ะฟัะพัะธะปะต

  '
is_easter_egg: false
is_feed: true
is_story: false
