caption: "Серьезная женщина ищу мужчину для отношений. Живу одна, имею свой небольшой\
  \ бизнес, хочется настоящей любви \U0001F970\n\n❣️ Знакомства по ссылке ❣️\n❤️ Переходи\
  \ в профиль ❤️\n\n#знакомствадлясерьезныхотношений #знакомство #знакомства #ищупарня\
  \ #ищудевушку #ищулюбовь #знакомстваукраина #знакомствароссия \n#знакомство#знакомства\
  \ #знакомстваонлайнэ #знакомствадлясерьезныхотношений  #dating #datingUkraine #datingRussia\n"
is_easter_egg: false
is_feed: true
is_story: false
