caption: "Мне кажется или уже все забыли про нормальные человеческие отношения???\
  \ \nКто желает познакомиться жду по ссылке в профиле\n\n#знакомствадлясерьезныхотношений\
  \ #знакомство #знакомства #ищупарня #ищудевушку #ищулюбовь #знакомстваукраина #знакомствароссия\
  \ \n#знакомство#знакомства #знакомстваонлайнэ #знакомствадлясерьезныхотношений \
  \ #dating #datingUkraine #datingRussia\n"
is_easter_egg: false
is_feed: true
is_story: false
