caption: "rate the photo from 1 to 10\U0001F609\U0001F31F\n\nlink in bio⬅️❤️\n\n#знакомствадлясерьезныхотношений\
  \ #знакомство #знакомства #ищупарня #ищудевушку #ищулюбовь #знакомстваукраина #знакомствароссия\
  \ \n#знакомство#знакомства #знакомстваонлайнэ #знакомствадлясерьезныхотношений \
  \ #dating #datingUkraine #datingRussia\n"
is_easter_egg: false
is_feed: true
is_story: false
