caption: "Всем привет, много работаю и времени на знакомство нету,но знали бы вы как\
  \ мне одиноко, хочется заботы и так далее. Пишите звоните я буду рада знакомству\n\
  \n❣️ Знакомства по ссылке ❣️\n❤️ Переходи в профиль ❤️\n\n#знакомствадлясерьезныхотношений\
  \ #знакомство #знакомства #ищупарня #ищудевушку #ищулюбовь #знакомстваукраина #знакомствароссия\
  \ \n#знакомство#знакомства #знакомстваонлайнэ #знакомствадлясерьезныхотношений \
  \ #dating #datingUkraine #datingRussia\n"
is_easter_egg: false
is_feed: true
is_story: false
