caption: "Тебе не будет одиноко на новый год? Переходи по ссылке в профиле и познакомся\
  \ с девушкой \nWon't you be lonely for the new year? Follow the link in the profile\
  \ and meet a girl\n"
is_easter_egg: false
is_feed: true
is_story: false
